In [1]:
import sqlite3
import pandas as pd

In [10]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"

df = pd.read_csv(url)

df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
conn = sqlite3.connect(':memory:')

df.to_sql(
    "TIPS",
    conn,
    index=False,
    if_exists='replace'
)

244

In [12]:
query = """
SELECT day,
COUNT(*) as Total
FROM TIPS
GROUP BY day
"""

pd.read_sql(query, conn)

    day  Total
0   Fri     19
1   Sat     87
2   Sun     76
3  Thur     62

In [13]:
query2 = """
SELECT sex,
AVG(total_bill) as AverageBill
FROM TIPS
GROUP BY sex
"""

pd.read_sql(query2, conn)

      sex  AverageBill
0  Female    18.056897
1    Male    20.744076